### ISSUE TITLE
Difference between W+ and W++

### ISSUE THREAD

**Issue by lzhbrian** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#12]
What's the difference between W+ and W++?

Is it **W++** outputting an **additional smallest feature map** ![equation](https://latex.codecogs.com/gif.latex?C%20%5Cin%20%5Cmathbb%7BR%7D%20%5E%20%7B4%20%5Ctimes%204%20%5Ctimes%20512%7D) to replace the constant input of the pretrained stylegan2 generator (as introduced in section 3.1 in the paper)?

Thanks!

**Comment by zyainfal** [comment]
Yes

**Comment by lzhbrian** [comment]
Got it, thanks for the quick reply!
