### ISSUE TITLE
Dataset preprocess

### ISSUE THREAD

**Issue by eveningglow** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#13]
Hi, thank you for your great work!

I got some questions about dataset preprocess

In the paper, it is written that CelebA, CelebA-HQ, FFHQ, and StyleGAN-generated images are used as training datasets.

All of these datasets are already aligned (e.g., eye location alignment), but I think the alignment can be slightly different for each dataset (e.g., different alignment between CelebA and FFHQ).

Did you apply an additional alignment on these datasets to remove this difference, or just use without an additional alignment?

Thank you!

**Comment by zyainfal** [comment]
It may train a better model if all face aligned in the same way, but we didn't do an additional alignment in our experiments.

**Comment by eveningglow** [comment]
Thank you for your reply! 

I got some more questions about the training dataset for FaceForensics ++ experiments, 

* You used CelebA, CelebA-HQ, FFHQ and StyleGAN-generated images. What size of images are used to train your model? I wonder it because only CelebA has 178x218 images, while other datasets have 1024x1024 images.

* How did you resize each training dataset to the target size (e.g., 178x178 center-crop and resize to the target size on CelebA, just resize to the target size on FFHQ, etc)?

* For the StyleGAN-generated images, did you use generated images uploaded on this website (https://drive.google.com/drive/folders/1-0YhtXe_oE2ei0R471X33a_NJyY5dVge)?

Thank you!

**Comment by zyainfal** [comment]
For FaceForensics ++ experiments, all images are resized to 256x256. 
That is to say, you need a stylegan2 model for 256x256 face generation.
------------------------------------------------------------------------------------
I didn't use those data, but you can use them. It should boost the model performance (even at a small margin).
