### ISSUE TITLE
Questions on the FaceForensics++ experiment

### ISSUE THREAD

**Issue by HoiM** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#15]
Hi, thank you for your great work. 

I have some questions regarding your FaceForensics++ experiments. 

Can you let me know how you define the source and target pairs after getting the 10000 aligned faces?

**Comment by zyainfal** [comment]
Well, it's simple:
1.  According to the pairs determined by FaceForensics++, the face on video-A frame-N is swapped to video-B frame-N
2.  If this process fails, we use another (most) frontal face in  video-A as the source, and swap it to video-B

**Comment by HoiM** [comment]
> Well, it's simple:
> 
>     1. According to the pairs determined by FaceForensics++, the face on video-A frame-N is swapped to video-B frame-N
> 
>     2. If this process fails, we use another (most) frontal face in  video-A as the source, and swap it to video-B

Thank you for your reply!
