### ISSUE TITLE
About the "Objective function of HieRFE"?

### ISSUE THREAD

**Issue by jo-dean** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#16]
hello, when i read the paper,i found the " a pair of input image x and its reconstruction image ˆx".
Does the "x" mean the cat(S_img,T_img)?
And what's the meaning of "reconstruction image ˆx"? How to generate it?
thank you so much!

**Comment by zyainfal** [comment]
In reconstruction training, there is no concept of source and target.
X means individual face image.

For generating X_hat, we use HieRFE to encode a face image X to its latent codes, then feed StyleGAN2 these latent codes to  get  reconstructed face image X_hat.

**Comment by jo-dean** [comment]
Thanks for your quick reply,it's a great job.
