### ISSUE TITLE
About the input of swapper?

### ISSUE THREAD

**Issue by jo-dean** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#19]
Hello,when i debug the _inference.py_,
in the line`swapped_lats = self.swapper(idd_lats, att_lats)`
I found the dim of idd_lats and att_lats is **[1,18,512]**.
but in the paper,_Ls_high_ and _Lt_high_ are the input of FTM, the dim is **[1,14,512]**,did't include the _Lt_low_

![image](https://user-images.githubusercontent.com/38728358/134450665-a2085347-3d1d-4669-9182-99b16e4c8663.png)
Is there something different？
thank you!

**Comment by zyainfal** [comment]
Please check the forward function of swapper:
https://github.com/zyainfal/One-Shot-Face-Swapping-on-Megapixels/blob/edfb9c85120fb9fd32386dca1465a70694b1207c/inference/megafs.py#L417-L435
where
https://github.com/zyainfal/One-Shot-Face-Swapping-on-Megapixels/blob/edfb9c85120fb9fd32386dca1465a70694b1207c/inference/inference.py#L73
which means the lower 4 latents is not used by FTM but other 14 latents are used.

**Comment by jo-dean** [comment]
thank you! It's my fault.
