### ISSUE TITLE
will the code release?

### ISSUE THREAD

**Issue by jinfagang** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#2]
will the code release?

**Comment by zyainfal** [comment]
In close future, we don't have this plan. 

Actually, I haven't rearranged/refined the codes. 

Maybe a month later or so, I would release the inference codes on CelebA-HQ-Mask.

**Comment by molo32** [comment]
any news on when the code will be released?

**Comment by zyainfal** [comment]
Yes, the inference code will be released before July 2021 if everything goes right.

**Comment by zyainfal** [comment]
Hi guys, I just update the inference code. Therefore issue closed.

**Comment by zyainfal** [comment]
Hi guys, I just update the inference code. Therefore issue closed.
