### ISSUE TITLE
Bad test examples

### ISSUE THREAD

**Issue by hallwaypzh** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#22]
I have tried the inference code on the examples in the paper (Figure 5.), however this one goes horribly wrong
, 
![8 jpg_9 jpg](https://user-images.githubusercontent.com/29053705/136660857-4d1b8eb0-da2c-4e4f-8284-2ab04d54a4df.jpg)
this is the picture generated by stylegan
![sg2](https://user-images.githubusercontent.com/29053705/136660928-a6479b13-192d-4d55-a090-f2bb64c1b4a9.png)

I'm using ftm method btw

**Comment by zyainfal** [comment]
Nope
