### ISSUE TITLE
Swap result is black

### ISSUE THREAD

**Issue by cwalt2014** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#28]
HI,

I set up the environment exactly as you described. I checked the images before they became tensors in preprocess and are correct. After swap, I do this:

```
        swapped_face = self.postprocess(swapped_face, tgt_face_rgb, tgt_mask)
        result = np.hstack((src_face_rgb[:,:,::-1], tgt_face_rgb[:,:,::-1], swapped_face))
        cv2.imshow('result', result)
        cv2.waitKey(0)
```
The resulting image is black. Any idea what is wrong? Any other step I can do to debug?

Thanks!

**Comment by zyainfal** [comment]
You may check the result of _**swapped_face**_ here. Is it black?
swapped_face = self.postprocess(_**swapped_face**_, tgt_face_rgb, tgt_mask)

**Comment by cwalt2014** [comment]
I got it working with the masks you recommended. I tried using this code to create the mask on the fly:

https://github.com/zllrunning/face-parsing.PyTorch/blob/master/evaluate.py

But it doesn't work. What code do I need to use to create masks that work with your model?

Thanks!

**Comment by cwalt2014** [comment]
Got it, just needed to create the correct mask. Thanks!

**Comment by cwalt2014** [comment]
Got it, just needed to create the correct mask. Thanks!

**Comment by flynnamy** [comment]
Same problem. How do you solve it? I use GT mask of CelebAHQ. @cwalt2014

**Comment by flynnamy** [comment]
Hi,I check that swapped_face is not black, any suggestions? @zyainfal

**Comment by zyainfal** [comment]
If swapped_face is not black,  your mask should be incorrect.
