### ISSUE TITLE
How can you keep the background so well ?

### ISSUE THREAD

**Issue by NewCoderQ** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#3]
What a great work!
As far as i know, styleGan will change the background, how can you keep the background so well ?

**Comment by zyainfal** [comment]
Just by segmentation because face-swapping doesn't care about the background.

So, we only swap the face region.

**Comment by zyainfal** [comment]
Hi, the inference code is released, and you can find more face fusion details.
And this issue is going to be closed.
Hope you enjoy it.

**Comment by zyainfal** [comment]
Hi, the inference code is released, and you can find more face fusion details.
And this issue is going to be closed.
Hope you enjoy it.
