### ISSUE TITLE
where should I place the stylegan2-pytorch directory

### ISSUE THREAD

**Issue by Georgefwt** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#30]
In your [README.md](https://github.com/zyainfal/One-Shot-Face-Swapping-on-Megapixels/blob/main/inference/README.md), You mentioned that `Put two provided files under stylegan2-pytorch directory`, but I can't find this directory in your repo.
So, is this mean I should download stylegan2-pytorch from [here](https://github.com/rosinality/stylegan2-pytorch) ,and put stylegan2-pytorch in your repo?
If so, which directory should I place? Thanks.

**Comment by zyainfal** [comment]
When you download the stylegan2-pytorch, put our codes under the stylegan2-pytorch folder as follows:
- stylegan2-pytorch
   -- their codes
   -- our codes
