### ISSUE TITLE
in megafs.py,  ModuleNotFoundError: No module named 'op'?

### ISSUE THREAD

**Issue by Dian-Yi** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#6]
We are all chinese people, i describe the problem using chinese for convenience.
非常感谢你的工作，我测试你的inference demo 发现缺少一些函数。希望你能够将inference的demo运行完整。
谢谢。

**Comment by zyainfal** [comment]
因为op是StyleGAN2的模块，要先按照[stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch)配置StyleGAN2的环境，因为包含gcc，cuda版本兼容的问题，需要你在自己的服务器上配置。

As stated in README.md, you need to implement StyleGAN2 as a prerequisite, including gcc compiler. 
Please refer [stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch) for details.

**Comment by willyzw1221** [comment]
If possible, please write down how to run the code in detail, thank you.

**Comment by zyainfal** [comment]
1. Implement stylegan2, see [stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch)
2. Download CelebA-HQ and CelebAMask-HQ
3. Put two provided files under *stylegan2-pytorch* directory, then run:

> python inference.py \
> 
> --swap_type [ftm/injection/lcr] \
> 
> --img_root [CelebAHQ-PATH] \
> 
> --mask_root [CelebAMaskHQ-PATH] \
> 
> --srcID [INT-NUMBER] \
> 
> --tgtID [INT-NUMBER]

where *swap_type* means which face transfer module you use, *img_root * is the CelebAHQ path, *mask_root* is the CelebAMaskHQ path, *srcID* and *tgtID* represent the image number of the CelebAHQ dataset.

**Comment by zyainfal** [comment]
And you need to download the pretrained weights:

[Baidu Cloud](https://pan.baidu.com/s/1DPNnU9zmkEdef6WT79J5Wg) (access code: 7nov)

[Google Drive](https://drive.google.com/drive/folders/1XDakvzNHDtC7G1d1Zn8MjPbmen4LKLPw?usp=sharing)

**Comment by willyzw1221** [comment]
> And you need to download the pretrained weights:
> 
> [Baidu Cloud](https://pan.baidu.com/s/1DPNnU9zmkEdef6WT79J5Wg) (access code: 7nov)
> 
> [Google Drive](https://drive.google.com/drive/folders/1XDakvzNHDtC7G1d1Zn8MjPbmen4LKLPw?usp=sharing)


I have downloaded these models.

**Comment by zyainfal** [comment]
If you have followed all steps above, you should be able to use the inference code.

If `No module named 'op'` is your problem, then you didn't follow the instructions of stylegan2-pytorch correctly.

Actually, step 1 is the most difficult step for users, as you need to compile `.cu` files by yourself.

**Comment by lyumingzhi** [comment]
Hi, would you like to explain more details of step one, especially compile .cu files?

**Comment by zyainfal** [comment]
Well, you can follow these steps:
1. update your gcc version to 7.3.1
2. install cuda 10.1
3. install pytorch 1.5.1
4. `git clone https://github.com/zyainfal/stylegan2-pytorch.git`
5. `cd stylegan2-pytorch` and test if you can `convert weight from official checkpoints` or `generate samples` (if you can, then everything you need to do for stylegan2 environment is done)

**Comment by zyainfal** [comment]
For compile `.cu` files, `stylegan2-pytorch` has done for you (if you have right gcc and cuda version).

**Comment by alessiabertugli** [comment]
Sorry for bothering you again. I was able to make the procedure you mentioned in the bulleted list above (both converting the checkpoint and generate samples correctly) but it still gives the error "No module named 'op'".
Nevertheless, when I run the command from stylegan2-pytorch
python stylegan2-pytorch/convert_weight.py --repo stylegan2/ stylegan2-ffhq-config-f.pkl
I can see the following output:
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Preprocessing... Loading... Done.

Can you help me with this issue, please? Thanks.

**Comment by zyainfal** [comment]
Do you put my codes under stylegan2-pytorch directory?

**Comment by alessiabertugli** [comment]
Ok, now it works. Thanks.

**Comment by zyainfal** [comment]
Great!
